### ISSUE TITLE
resolveddomains.txt no data entry

### ISSUE THREAD

**Issue by x1mdev** [x1mdev/ReconPi#1]
The grep function needs to be a bit more specific, it does `grep $URL >> domains.txt` and if there is an empty subdomain like `.sub.domain.tld` it will give an error:

``` bash

[+] Subfinder scan complete, checking which domains resolve..
host: '' is not in legal name syntax (unexpected end of input)
[+] Resolved domains written to resolveddomains.txt

```

It still writes the output but it's a bit messy

**Comment by ebelties** [comment]
This has been fixed with the Regular Expression:
```
cat $ROOT/$1/$1.txt | grep -P "([A-Za-z0-9]).*$1" >> $ROOT/$1/domains.txt
```

**Comment by x1mdev** [comment]
Ah, great job @ebelties :100:
