### ISSUE TITLE
Please don't apt update/upgrade -y in the install script

### ISSUE THREAD

**Issue by jdodds** [x1mdev/ReconPi#3]
```sh
echo "[+] Getting the basics..";
sudo apt-get update -y;
sudo apt-get upgrade -y;
```

This could hose people's setups :(

**Comment by jdodds** [comment]
Disregard this, I misread! Sorry!

**Comment by x1mdev** [comment]
It's for the Raspberry Pi, it should not hose people's setup unless you run this script on something different than the Pi
