### ISSUE TITLE
sublert.py ImportError: No module named 'tld'

### ISSUE THREAD

**Issue by ActivateDZA** [x1mdev/ReconPi#44]
**Describe the bug**
running recon on a tld I get a traceback and an error telling me it cannot import module named 'tld' even though it is a fresh install and followed the easy install method.

**To Reproduce**
1. Install Hypriot image (version 1.10.0)
2. Login to PI
3. install using curl -L https://raw.githubusercontent.com/x1mdev/ReconPi/master/install.sh | bash
4. recon domain

**Expected behavior**
I expect to get no errors

**Screenshots**
[image](https://user-images.githubusercontent.com/2852188/68090310-003de680-fe7b-11e9-9066-b65d5589c662.png)

**Desktop (please complete the following information):**
 - OS: Hypriot image (version 1.10.0)
 - Version 1.10.0

**Additional context**
I followed the instructions listed here
https://x1m.nl/posts/recon-pi/

**Comment by x1mdev** [comment]
Hmm that’s weird, can you navigate to the tools/sublert directory and run `pip3 install -r requirements.txt`? It seems to work on my device with a fresh install

**Comment by ActivateDZA** [comment]
Hi x1mdev,

I ran the command
![image](https://user-images.githubusercontent.com/2852188/68236340-a6b9f100-000d-11ea-83af-d349e989dab4.png)

and it fixed the issue
![image](https://user-images.githubusercontent.com/2852188/68236360-b0435900-000d-11ea-9c03-ae1fc8c2e098.png)

I think the issue was during the installation pip3 did not get installed for some reason hence why the issue.

**Comment by x1mdev** [comment]
That’s odd, but I’m glad the issue is fixed :)
