### ISSUE TITLE
Tool definition error, should Httprobe change to fprobe

### ISSUE THREAD

**Issue by taielab** [x1mdev/ReconPi#64]
**Describe the bug**

Httprobe has no -prefer-https parameter.

**Expected behavior**
<img width="524" alt="图片" src="https://user-images.githubusercontent.com/52345183/86764491-a8dfbe00-c07a-11ea-9963-11103e831fa1.png">

**Screenshots**
<img width="694" alt="图片" src="https://user-images.githubusercontent.com/52345183/86764071-5d2d1480-c07a-11ea-9b2f-2305e5f48eff.png">

**Additional context**
 Httprobe change to fprobe

**Comment by x1mdev** [comment]
Are you using the latest version of `httprobe`? It looks like the flag is present when I use `httprobe -h`:

```
httprobe -h
Usage of httprobe:
  -c int
    	set the concurrency level (split equally between HTTPS and HTTP requests) (default 20)
  -method string
    	HTTP method to use (default "GET")
  -p value
    	add additional probe (proto:port)
  -prefer-https
    	only try plain HTTP if HTTPS fails
  -s	skip the default probes (http:80 and https:443)
  -t int
    	timeout (milliseconds) (default 10000)
```
