### ISSUE TITLE
add

### ISSUE THREAD

**Issue by spazbg** [x1mdev/ReconPi#71]
Can you add to the project option for Discord webhook?

**Comment by maverickNerd** [comment]
Sadly, We don't have any plan for enabling discord webhook. Most of the people use slack for recon results.

**Comment by spazbg** [comment]
I think its a cool feature, personally I prefer discord, and maybe it's not so hard to be implemented. 
If you wanna check this
https://github.com/ChaoticWeg/discord.sh
https://jasonloong.com/2018/sending-linux-variables-to-discord-webhook-from-linux-bash-shell-script/
