### ISSUE TITLE
Nuclei missing tamplates and wrong path

### ISSUE THREAD

**Issue by spazbg** [x1mdev/ReconPi#74]
Nuclei missing tamplates for basic-detacions and brute-force
![alt text](https://i.imgur.com/SIp4BXt.png)

AND

Nuclei missing part of the path to the template

![alt text](https://i.imgur.com/hsaT6bu.png)

**Comment by maverickNerd** [comment]
No, just checked that nuclei changed the name of few folders, we are using nuclei --update-templates command to install templates, which will actually install templates in root folder not in tools. I will fix this asap

**Comment by maverickNerd** [comment]
fixed.
