### ISSUE TITLE
Issue with wordlist in startBruteForce

### ISSUE THREAD

**Issue by Anu-bhav** [x1mdev/ReconPi#76]
cat "$SUBS"/hosts | parallel -j 5 --bar --shuf gobuster dir -u {} -t 50 -w wordlist.txt -l -e -r -k -q -o "$DIRSCAN"/"$sub".txt
/home/admin/go/bin/gobuster dir -u "$line" -w "$WORDLIST"/wordlist.txt -e -q -k -n -o "$DIRSCAN"/out.txt

the wordlist.txt is not copied to the wordlists folder found in the resultdir anywhere in the recon.sh script

**Comment by maverickNerd** [comment]
Yes I don't think enabling directory bruteforcing as part of reconpi  is good since it takes lot of time, command is given just for a reference, feel free to change the name of wordlist file or path as per your convenience in your local change
