### ISSUE TITLE
Add GF into workflow

### ISSUE THREAD

**Issue by Anu-bhav** [x1mdev/ReconPi#77]
GFSCAN="$RESULTDIR/gfscan"

: 'Use gf to find secrets in meg file'
startGfScan(){
	startFunction "Gf scan in meg files"
	cd "$SUBS"/meg
	for i in `gf -list`; 
	do
		gf ${i} > "$GFSCAN"/"${i}".txt
		[[ -s "$GFSCAN"/"${i}".txt ]] || rm "$GFSCAN"/"${i}".txt	
	done
	cd -
}

startGfScan # add function after startMeg to run

**Comment by maverickNerd** [comment]
Can you send a Pull request with change, we would love to have contribution.

**Comment by maverickNerd** [comment]
Merged your change.
