### ISSUE TITLE
"unable to cache TLDs in file /usr/local/lib/python3.7/dist-packages/tldextract/.tld_set"

### ISSUE THREAD

**Issue by spazbg** [x1mdev/ReconPi#80]
After adding the GitHub API key I am having this error:

"unable to cache TLDs in file /usr/local/lib/python3.7/dist-packages/tldextract/.tld_set: [Errno 13] Permission denied: '/usr/local/lib/python3.7/dist-packages/tldextract/.tld_set'"

So after take a look at /usr/local/lib/python3.7/dist-packages/tldextract/ folder the actual name of the .tld_set file was .tld_set_snapshot so I have to chmod +775 the file and rename it to .tld_set and now its OK

**Comment by maverickNerd** [comment]
never faced this myself, also "/usr/local/lib/python3.7/dist-packages/tldextract/.tld_set" is python internal libs, we have no control on it from our recon script, this seems something related to your environment, try running this script as root.
