### ISSUE TITLE
EyeWitness doesn't work with RaspbianOS.

### ISSUE THREAD

**Issue by spazbg** [x1mdev/ReconPi#84]
![image](https://user-images.githubusercontent.com/22222777/92159334-e623ba80-ee35-11ea-9669-6c797068c4c8.png)

**Comment by udpsec** [comment]
me too

**Comment by maverickNerd** [comment]
Oops, we need to see what we can do then, may be we will put up a if statement to check arch and use aquatone on raspberry Pi and eyewitness on x86.

**Comment by maverickNerd** [comment]
Hi,

I pushed the fix to it, can you update your ReconPi, by going to $HOME/ReconPi, do git pull, and test if aquatone is working now.

**Comment by spazbg** [comment]
Perfect
![IMG_20200906_105259](https://user-images.githubusercontent.com/22222777/92321036-42056380-f02f-11ea-9796-9faf76ea2969.jpg)
