### ISSUE TITLE
"grep: .: Is a directory" error

### ISSUE THREAD

**Issue by spazbg** [x1mdev/ReconPi#87]
![image](https://user-images.githubusercontent.com/22222777/92716521-97ab7a00-f367-11ea-8b15-6f62bfd13d68.png)

Aways get this error from Gf Scan, any ideas how to fix it?

**Comment by maverickNerd** [comment]
Yes as of now ignore this error, thing is there are lot of gf pattern in gf directory and some expects directly a file on stdin, I will try fixing it later on with some other logic.

With the current logic, whatever gf pattern it can run, all those are running fine and storing results of those

**Comment by maverickNerd** [comment]
You will not see this error now, please update your ReconPi.
