### ISSUE TITLE
Naabu -p flag problem

### ISSUE THREAD

**Issue by spazbg** [x1mdev/ReconPi#94]
Naabu has a new version - v.2 maybe that's the problem
![image](https://user-images.githubusercontent.com/22222777/94815290-0b8af080-0403-11eb-8be7-0b12d7cefe01.png)

**Comment by maverickNerd** [comment]
hey, thanks for telling us.

I fixed it. Just pull the change and install: cd $HOME/ReconPi;git pull;./install.sh

It is hard to keep up with Project discovery tools, they update the tools very frequently, it is good for us, but they keep increasing the version number for the tool path which is annoying.

**Comment by spazbg** [comment]
True true :D
